### ISSUE TITLE
Issue reading castep's lattice_abc

### ISSUE THREAD

**Issue by jryates** [SMTG-Bham/sumo#107]
Line 81 of io/castep.py is
`lengths_and_angles = lattice_abc[1:]`
This causes an error, I think the correct line is
`lengths_and_angles = lattice_abc`

This is the section of code which reads a lattice_abc block - specifically the case in which we haven't passed a unit line (and hence we don't need to strip out the 1st row)

I didn't make a pull request because the run then gives a warning:
    DeprecationWarning: from_lengths_and_angles is deprecated Use Lattice.from_parameters instead. This will be removed in v2020.*
 So I thought it might be better to fix the two things at the same time. I'm still getting the hang of python, so I'll defer to @ajjackson

**Comment by ajjackson** [comment]
Thanks for reporting, I'll get to this when I can!

**Comment by ajjackson** [comment]
Thanks for the investigation and reminder Jonathan, I'll take a look.

**Comment by ajjackson** [comment]
@utf I've had a look at this and run into a problem: `Lattice.from_parameters` does not generate the cell in lower-triangular form as CASTEP does. This would give an inconsistent structure if the atom positions are given in absolute coordinates.

Do you know of any functionality in Pymatgen to standardise the cell to lower-triangular? It's easy in ASE...

**Comment by ajjackson** [comment]
@jryates Looking at `subroutine cell_abc_to_cart_lattice(a,b,c,alpha,beta,gamma,mycell)` in the CASTEP source, it is somewhat complex and uses the spacegroup. Perhaps we should refuse to read .cell files that use `lattice_abc` with `positions_abs`, rather than risk getting it wrong.
