### ISSUE TITLE
A lot of link cannot be found

### ISSUE THREAD

**Issue by haiyuanwang2020** [SMTG-Bham/sumo#225]
Dear Developer,

I am planning to see how this SUMO works, but a lot of links are not found.
Would you please check this issue?

Thank you in advance.

Best regards,
Haiyuan.

**Comment by utf** [comment]
This has been fixed.

**Comment by haiyuanwang2020** [comment]
Dear Alex,

Many thanks for fixing it. I am sorry for the long-time silence.
I am enjoying sumo quite a lot these days. It is such a nice tool 🙂
Please feel free to close the issue ticket.

Best regards,
Haiyuan.

________________________________
