### ISSUE TITLE
strange DOS shape

### ISSUE THREAD

**Issue by giacsport** [SMTG-Bham/sumo#232]
Dear all,
I am trying to understand what is going on.
I get this weird DOS plot (sumo-dosplot) for a system where the bandgap reported by sumo-bandstats is apparently less than 0.1 eV
The DOS itself seem those of a wide bandgap semiconductor...(~2.5 eV)

Indirect band gap: 0.080 eV
Direct band gap: 0.091 eV
  k-point: [0.00, 0.06, 0.00]
  k-point indices: 28
  Band indices: 916, 917

Valence band maximum:
  Energy: 0.552 eV
  k-point: [0.06, 0.00, 0.00]
  k-point location: between \Gamma-A
  k-point indices: 26
  k-point degeneracy: 1
  Band indices: 916

Conduction band minimum:
  Energy: 0.633 eV
  k-point: [0.00, 0.06, 0.00]
  k-point location: between \Gamma-A
  k-point indices: 28
  k-point degeneracy: 1
  Band indices: 917

Using parabolic fitting of the band edges

Hole effective masses:
  m_h: -0.540 | band 916 | [0.06, 0.00, 0.00] -> [0.00, 0.50, 0.00] (A)
  m_h: -0.168 | band 916 | [0.06, 0.00, 0.00] -> [0.00, 0.00, 0.00] (\Gamma)
[dos.pdf](https://github.com/SMTG-Bham/sumo/files/13853997/dos.pdf)

It is an interface between perovskite and bulk GeO2 system.
I do definitely struggle to understand what is going on.
It is not the first time I get such results, which make me even more confused.

The code is installed in italian supercompute center with the standard installation procedure. The same results (the dos) are obtained in my local cluster.

Here my INCAR

SYSTEM = BAPI4

# xc
GGA = PE

#surface dipole
IDIPOL = 3
LDIPOL = .TRUE.
LVHAR=.TRUE.

LREAL = Auto
PREC= Accurate

ENCUT=600.00

ISMEAR = 1
SIGMA  = 0.000011

#electronic RELAXATION
NELMIN = 4
NELM = 800

ISIF = 2

IBRION = 1
NFREE  = 10
ADDGRID = .TRUE.

#accuracy of the calculation
EDIFF = 1.E-5 ! 1.E-5
EDIFFG= -0.05 ! -0.05

AMIN=0.01
#ionic steps
NSW = 0
IVDW = 12

AMIX     = 0.1
BMIX     = 3.00

LORBIT=11
NEDOS=2000
ICHARG=11

POTCAR are standard ones (Sn and Ge with d)

Any suggestion?
Thanks
Giacomo

**Comment by utf** [comment]
Can you try using tetrahedron method instead of Methfessel-Paxton for the smearing (`ISMEAR = -5`). MP smearing is not recommended for insulators.

**Comment by giacsport** [comment]
Dear utf, 
thanks!
Apparently ISMEAR=-5 and the KPOINTS generated with sumo-kgen are not compatible

 scaLAPACK will be used selectively (only on CPU)
 LDA part: xc-table for Pade appr. of Perdew
 -----------------------------------------------------------------------------
|                                                                             |
|     EEEEEEE  RRRRRR   RRRRRR   OOOOOOO  RRRRRR      ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     EEEEE    RRRRRR   RRRRRR   O     O  RRRRRR       #       #       #      |
|     E        R   R    R   R    O     O  R   R                               |
|     E        R    R   R    R   O     O  R    R      ###     ###     ###     |
|     EEEEEEE  R     R  R     R  OOOOOOO  R     R     ###     ###     ###     |
|                                                                             |
|     Error reading KPOINTS file.                                             |
|     The error occurred at line: 40.                                         |
|                                                                             |
|       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----       |
|                                                                             |
 -----------------------------------------------------------------------------

 I think it is matter of different IBZKPT.
By the way, my system is not an insulator (Gap~0)

Many thanks,
G

**Comment by utf** [comment]
Tetrahedron method is only for DOS calculations (not band structures). If your system is metallic you should use a large SIGMA. E.g., `SIGMA = 0.2`.

**Comment by giacsport** [comment]
Many thanks! That was the issue. 
I was inadvertently using sigma values that were far too small for DOS calculations. With SiGMA 0.1-0.2, the behaviour becomes correct again. Thanks again.
G
