### ISSUE TITLE
Separating spin-up and spin-down contributions in sumo-bandplot output .dat file

### ISSUE THREAD

**Issue by JaafarMehrez** [SMTG-Bham/sumo#240]
Using  `sumo-bandplot -spin 1` or `sumo-bandplot -spin -1`, one is able to obtain the bandstructure with either spin-up or spin-down channels, however, the created .dat file will contain both spin-up and spin-down contributions. I would like to ask whether one could have those contributions in two separated .dat files?

**Comment by ajjackson** [comment]
You could use the unix `cut` program to remove the unwanted columns from the file. Just watch out for the header; the extra `#` means the header has one more entry and the indices are offset.

e.g. to get the spin-up component from a file with s,p,d components:
```bash
FILENAME=Ni_dos.dat
head -n 1 $FILENAME | cut -d ' ' -f 2,3,5
tail -n +2 $FILENAME | cut -d ' ' -f 1,2,4
```

It shouldn't take much extra work to turn that into a shell function or script that takes a .dat file as input and writes a couple of new ones, and would be a bit easier to share/maintain than a Summo fork.
