### ISSUE TITLE
sumo-dosplot showing error ValueError: invalid literal for int() with base 10: '!'

### ISSUE THREAD

**Issue by ihtishamqabid** [SMTG-Bham/sumo#242]

**Comment by utf** [comment]
Please can you provide more information on exactly what command you're running and if possible provide the vasprun.xml

**Comment by ihtishamqabid** [comment]
[vasprun.zip](https://github.com/SMTG-Bham/sumo/files/15470536/vasprun.zip)
Thank you very much for your response. I am sorry. Actually, I was in a hurry so didn't write in detail; thought maybe if someone responds then .... Anyway, I used the command "sumo-dosplot". I am attaching the vasprun.xml file. sumo-bandplot works fine. Also, when I used the sumo-dosplot command for a vasp official tutorial vasprun.xml file, it worked like a charm but it is not working for my personal project. Also, I could use the plotdos.sh script to to plot the dos and there were no issues. So, I don't know what's going on. Note: I am new to VASP so I might make silly mistakes.

**Comment by ihtishamqabid** [comment]
I really appreciate your effort. Here is the KPOINTS file.
[KPOINTS.zip](https://github.com/SMTG-Bham/sumo/files/15473348/KPOINTS.zip)

**Comment by ihtishamqabid** [comment]
I found the specific issue. The issue is related to file path. Usually I run the sumo-dosplot command where the vasprun.xml file is and that is a deep directory like /home/iq/Jobs/VASP/Na2Cr3As3/Encut 300/sigma 0.1 6x6x12/DOS and it contains <space> which causes the issue. I just copied the vasprun.xml file I shared with you in the Home folder and executed the sumo-dosplot command with no issue.

By the way, the sumo-bandplot command works fine even in such deep directories.

I guess, once someone starts using computers/phones, s/he should not name any file/folder containing space.

And thank you very much for your time you spent looking into my issue. Should I close this now?

**Comment by ajjackson** [comment]
It's good to hear that this isn't blocking your work any more 😄 

I would be interested to know exactly where things go awry: with proper use of pathlib etc. we shouldn't have to encounter problems like this.

**Comment by ajjackson** [comment]
Strange, the error message seems to blame the formatting of the KPOINTS file (finding "!" where it expected a number). But the one you uploaded looks fine.

**Comment by ihtishamqabid** [comment]
OK. Insha'Allah I will look into it. I will try removing the comments altogether first. I remember I had an INCAR file which looked fine to me but VASP reported error and I did a workaround by removing the comments and still do not know what wrong was there. Maybe some issue of similar type is present here. Actually, I write so many comments 😊 because I tend to forget what the tags mean, what are their default values and so forth and each time I have to look into vasp wiki; so irritating.
Anyway, Insha'Allah I will look into it. And, I can't thank you enough @utf, @ajjackson for the time you spent on my issue.

**Comment by ihtishamqabid** [comment]
If I remove the comments altogether from the KPOINTS file then it works fine. As soon as I add comments the issue emerges again. And, earlier I mentioned that if I copy the vasprun.xml file to the Home directory then there is no problem - that is so because I do not copy the KPOINTS file, containing comments, there.

**Comment by utf** [comment]
I'm going to close this now as I don't think this is an issue in sumo itself.

**Comment by ihtishamqabid** [comment]
Thank you everyone.
