### ISSUE TITLE
Effective mass

### ISSUE THREAD

**Issue by kuber05** [SMTG-Bham/sumo#243]
Hello, I have a question regarding the interpretation of the effective mass. Which effective mass of the hole and electron should I consider?

Additionally, why is the electron effective mass calculated for V→U and V→G and not for V→X and X→R, even though the latter path is shown in the band plot (attached)? Similarly, why is the hole effective mass not calculated for X→V but is calculated for X→U?
[band.pdf](https://github.com/SMTG-Bham/sumo/files/15468881/band.pdf)

Indirect band gap: 0.776 eV
Direct band gap: 0.779 eV
  k-point: [0.50, 0.50, 0.00]
  k-point indices: 50
  Band indices: 366, 367

Valence band maximum:
  Energy: -2.966 eV
  k-point: [0.50, -0.00, 0.00]
  k-point location: X
  k-point indices: 46
  k-point degeneracy: 1
  Band indices: 366

Conduction band minimum:
  Energy: -2.190 eV
  k-point: [0.50, 0.50, 0.00]
  k-point location: V
  k-point indices: 50
  k-point degeneracy: 1
  Band indices: 367

Using parabolic fitting of the band edges

Hole effective masses:
  m_h: -7.948 | band 366 | [0.50, -0.00, 0.00] (X) -> [0.50, -0.00, 0.50] (U)
  m_h: -1.124 | band 366 | [0.50, -0.00, 0.00] (X) -> [0.00, 0.00, 0.00] (\Gamma)

Electron effective masses:
  m_e: 0.145 | band 367 | [0.50, 0.50, 0.00] (V) -> [0.50, -0.00, 0.50] (U)
  m_e: 2.940 | band 367 | [0.50, 0.50, 0.00] (V) -> [0.00, 0.00, 0.00] (\Gamma)

**Comment by utf** [comment]
Hi @kuber05, there was a bug in sumo for the effective mass labels. This should now be fixed.
