### ISSUE TITLE
How to change yellow band color to red bands in band strcture?

### ISSUE THREAD

**Issue by Moon121212** [SMTG-Bham/sumo#244]

**Comment by ajjackson** [comment]
There are docs here for general plot customisation: https://smtg-bham.github.io/sumo/customising-plots.html

e.g. to override the colours with a custom sequence
```
echo "axes.prop_cycle: cycler('color', ['blue', 'red'])" > tmp.mplstyle
sumo-bandplot --style tmp.mplstyle
```
