### ISSUE TITLE
GAMMA in xticks, how to fix it to Greek alphabet style

### ISSUE THREAD

**Issue by 1lifetime1** [SMTG-Bham/sumo#249]
### Discussed in https://github.com/SMTG-Bham/sumo/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **1lifetime1** August 30, 2024</sup>
![Uploading sumo_error.jpg…]()
</div>

**Comment by 1lifetime1** [comment]
![sumo_error](https://github.com/user-attachments/assets/57554707-432a-4036-9b60-a418684b666f)
now the figure is well uploaded, please help

**Comment by ajjackson** [comment]
Answered in [discussions](https://github.com/SMTG-Bham/sumo/discussions/248), please don't cross-post before waiting for a response.
