### ISSUE TITLE
High-symmetry points are not labelled when using non-sumo KPOINTS file

### ISSUE THREAD

**Issue by ekkowdg** [SMTG-Bham/sumo#251]
When I execute the sumo-bandplot command, the generated bandplot does not indicate the high symmetric points. I want to know where sumo reads the high symmetric points label when drawing the bandplot, KPOINTS or OUTCAR? I run the command in the folder after the execution of the vasp calculation task. I use the high symmetric point path generated from the seek-path website to write my own defined KPOINTS, is it necessary to use the band path generated by the sumo-kgen command?
[band.pdf](https://github.com/user-attachments/files/17645778/band.pdf)

**Comment by ajjackson** [comment]
It reads them from KPOINTS. The standard `sumo` workflow is to produce KPOINTS using `sumo-kgen`. This tool provides several ways of specifying the path, including a `--seekpath` option which uses the SeeK-path library. https://smtg-bham.github.io/sumo/sumo-kgen.html

I suggest having a play with this tool to understand what `sumo-bandplot` is looking for; you can add this information to an existing KPOINTS file if necessary.

**Comment by ekkowdg** [comment]
Many thanks for your replying!
