### ISSUE TITLE
having problem with sumo-kgen

### ISSUE THREAD

**Issue by scientistminion** [SMTG-Bham/sumo#252]
Hello! Thank you so much for the code, I love it! I encountered an issue today while using sumo-kgen. I am trying to create a k-path  for a supercell and the structure has some modifications and distortions. No matter what i tried the error looks the same:

[fk6671@della8 supercell]$ sumo-kgen
Traceback (most recent call last):
  File "/home/fk6671/.local/bin/sumo-kgen", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/fk6671/.local/lib/python3.11/site-packages/sumo/cli/kgen.py", line 415, in main
    kgen(
  File "/home/fk6671/.local/lib/python3.11/site-packages/sumo/cli/kgen.py", line 168, in kgen
    kpath, kpoints, labels = get_path_data(
                             ^^^^^^^^^^^^^^
  File "/home/fk6671/.local/lib/python3.11/site-packages/sumo/symmetry/kpoints.py", line 131, in get_path_data
    kpath = BradCrackKpath(structure, symprec=symprec, spg=spg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fk6671/.local/lib/python3.11/site-packages/sumo/symmetry/brad_crack_kpath.py", line 53, in __init__
    Kpath.__init__(self, structure, symprec=symprec)
  File "/home/fk6671/.local/lib/python3.11/site-packages/sumo/symmetry/kpath.py", line 47, in __init__
    self._seek_data = seekpath.get_path(std)
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fk6671/.local/lib/python3.11/site-packages/seekpath/getpaths.py", line 182, in get_path
    res = hpkot.get_path(
          ^^^^^^^^^^^^^^^
  File "/home/fk6671/.local/lib/python3.11/site-packages/seekpath/hpkot/__init__.py", line 158, in get_path
    np.array(structure[0]),
             ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable


Can you help me with that?

**Comment by ajjackson** [comment]
That's interesting, somehow the structure is lost by the time it goes to seekpath. Could you share a structure file that reproduces the problem? If you'd prefer not to share it in public you can send me an email - the address is on [this page](https://www.scd.stfc.ac.uk/Pages/Jackson,-Adam.aspx)

**Comment by ajjackson** [comment]
Thanks for sending a structure, I can reproduce the error, and the problem is not that Pymatgen cannot load the POSCAR 🤔

**Comment by ajjackson** [comment]
The None is coming from `spglib.refine_cell`

https://spglib.readthedocs.io/en/stable/api/python-api/spglib/spglib.html#spglib.refine_cell
> When the search failed, None is returned.

The Pymatgen `SpacegroupAnalyzer.get_symmetry_dataset()` method is also returning None, which is not a documented possibility.
https://pymatgen.org/pymatgen.symmetry.html

Looking a bit more into the source, we _should_ be getting a SymmetryUndeterminedError in this situation?
https://github.com/materialsproject/pymatgen/blob/0e65d35ae0b1df964639a48067b1a525979eec84/src/pymatgen/symmetry/analyzer.py#L74

@utf any thoughts on how to proceed here? Currently there doesn't seem to be any way to prevent this symmetry check so even if the user specifies P1 and an arbitrary path we hit this code and error.

**Comment by utf** [comment]
Normally the fix is to try a different symprec until you find one that works.

**Comment by ajjackson** [comment]
Good to know!

In this case it doesn't seem to help. Somehow this structure is toxic to spglib; I haven't seen such a thing before. Have tried a range of spglib versions as well.

I guess the next step is to see if the structure file can be massaged into a form that plays nicely, will have a play.

**Comment by utf** [comment]
I've also seen this bug if the structure has atoms directly on top of each other. Maybe that is the problem here too?

**Comment by ajjackson** [comment]
Aha! There are indeed some duplicate atoms. (It's a big file and they aren't at the top 😅 )

**Comment by scientistminion** [comment]
Yes! when i fix the file, the problem solved. Thank you so much! Sorry that I didnt realize about the duplicated atoms 😅
